package pl.edu.icm.saos.webapp.analysis.generator;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import pl.edu.icm.saos.webapp.analysis.request.UiySettings.UiyValueType;
import pl.edu.icm.saos.webapp.analysis.result.FlotChart.FlotSeries;

import com.google.common.base.Preconditions;

/**
 * 
 * An implementation of {@link FlotSeriesAggregator} handling aggregation of 
 * {@link FlotSeries} holding y-values being numbers (of occurrence of a specific phenomenon).   
 * 
 * @author Łukasz Dumiszewski
 */
@Service("numberFlotSeriesAggregator")
class NumberFlotSeriesAggregator implements FlotSeriesAggregator {

    
    
    private AggregatedSeriesXValueGenerator aggregatedSeriesXValueGenerator;
    
    
    
    //------------------------ LOGIC --------------------------
    
    /**
     * Aggregates the given series. Returns a flot series with one point. 
     * The x-value is generated by {{@link #setAggregatedSeriesXValueGenerator(AggregatedSeriesXValueGenerator)}
     * and y-value is a sum of y-values of the passed flotSeries.
     *  
     */
    @Override
    public FlotSeries aggregateFlotSeries(FlotSeries flotSeries, int flotSeriesIndex) {
        
        FlotSeries aggregatedFlotSeries = new FlotSeries();
        
        int sum = 0;
        
        for (Number[] point : flotSeries.getPoints()) {
            
            sum += point[1].intValue();    
            
        }
        
        aggregatedFlotSeries.addPoint(new Integer[]{aggregatedSeriesXValueGenerator.generateXValue(flotSeriesIndex), sum});
        
        return aggregatedFlotSeries;
        
    }

    @Override
    public boolean handles(UiyValueType uiyValueType) {
        
        Preconditions.checkNotNull(uiyValueType);
        
        return UiyValueType.NUMBER == uiyValueType;
        
    }

    
    
    //------------------------ SETTERS --------------------------
    
    @Autowired
    public void setAggregatedSeriesXValueGenerator(AggregatedSeriesXValueGenerator aggregatedSeriesXValueGenerator) {
        this.aggregatedSeriesXValueGenerator = aggregatedSeriesXValueGenerator;
    }

}
