package pl.edu.icm.saos.importer.simple;

/**
 * This package provides functionality of simple import.
 * Here 'simple' means 'from files generated by us from html or pdfs, not by using specialized api'. 
 * 
 * Some data is imported from generated files, because at the time of writing this importer
 * certain courts did not provide any API for downloading the judgment data in a sensible
 * format.
 * 
 * */
