//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 11:19:30 AM CEST 
//


package pl.edu.icm.saos.common.service;

public enum ServiceExecutionStatus {

    OK,
    ERROR;

    public static ServiceExecutionStatus fromValue(String v) {
        return valueOf(v);
    }

}
