package pl.edu.icm.saos.persistence.enrichment.model;

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import pl.edu.icm.saos.persistence.common.DataObject;
import pl.edu.icm.saos.persistence.common.StringJsonUserType;
import pl.edu.icm.saos.persistence.model.Judgment;

/**
 * 
 * Represents a data enrichement record generated by the external SAOS Enricher System. <br/>
 * A single data enrichment record stores one type of information for a given {@link Judgment}, e.g. 
 * referenced regulations related to the judgment.
 * 
 * @author Łukasz Dumiszewski
 */
@TypeDefs( {@TypeDef( name= "StringJsonObject", typeClass = StringJsonUserType.class)})
@MappedSuperclass
public abstract class AbstractEnrichmentTag extends DataObject {

	private int judgmentId;
    
    private String tagType;
    
    private String value;
    
    
    //------------------------ GETTERS --------------------------
    
    

    /**
     * The judgment that this tags adds information to.
     * @return
     */
    @Column(nullable=false)
    public int getJudgmentId() {
        return judgmentId;
    }


    /**
     * Tag type which specifies the sort of information provided by this tag. <br/> 
     * Not enum or other strict type in order to allow loose and independent cooperation between SAOS and SAOS Enricher System (
     * some tags generated by SAOS Enricher won't be used directly by SAOS but only exposed by RESTful API). The types recognizable
     * and used internally by SAOS are defined in {@link EnrichmentTagTypes}.
     */
    @Column(nullable=false)
    public String getTagType() {
        return tagType;
    }


    /**
     * String value of the tag in json format.
     */
    @Type(type = "StringJsonObject" )
    @Column(nullable=false)
    public String getValue() {
        return value;
    }
    
    
    
    //------------------------ SETTERS --------------------------


    public void setJudgmentId(int judgmentId) {
        this.judgmentId = judgmentId;
    }


    public void setTagType(String tagType) {
        this.tagType = tagType;
    }


    public void setValue(String value) {
        this.value = value;
    }

    
    //------------------------ HashCode & Equals --------------------------
    
    
    @Override
    public int hashCode() {
        return Objects.hash(this.judgmentId, this.tagType, this.value);
    }
    
    
    @Override
    public boolean equals(Object obj) {
        
        if (obj == null) {
           return false;
        }
        
        if (getClass() != obj.getClass()) {
           return false;
        }
        
        final AbstractEnrichmentTag other = (AbstractEnrichmentTag) obj;
        
        return Objects.equals(this.judgmentId, other.judgmentId)
                && Objects.equals(this.tagType, other.tagType)
                && Objects.equals(this.value, other.value);

    }


   
    
    //------------------------ toString --------------------------
    
    @Override
    public String toString() {
        return "JudgmentCorrection [judgmentId=" + judgmentId
                + ", tagType=" + tagType
                + ", value=" + value + "]";
    }


 


}
