package pl.edu.icm.saos.persistence.enrichment.model;

import java.util.Objects;

import javax.persistence.Cacheable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import pl.edu.icm.saos.persistence.common.DataObject;
import pl.edu.icm.saos.persistence.common.StringJsonUserType;
import pl.edu.icm.saos.persistence.model.Judgment;

/**
 * 
 * Represents a data enrichement record generated by the external SAOS Enricher System. <br/>
 * A single data enrichment record stores one type of information for a given {@link Judgment}, e.g. 
 * referenced regulations related to the judgment.
 * 
 * @author Łukasz Dumiszewski
 */
@Entity
@Table(uniqueConstraints={@UniqueConstraint(name="judgment_type_value_unique", columnNames={"fk_judgment", "tagType", "value"})})
@Inheritance(strategy = InheritanceType.JOINED)
@Cacheable(true)
@SequenceGenerator(name = "seq_enrichment_tag", allocationSize = 1, sequenceName = "seq_enrichment_tag")
@TypeDefs( {@TypeDef( name= "StringJsonObject", typeClass = StringJsonUserType.class)})
public class EnrichmentTag extends DataObject {

    
    private Judgment judgment;
    
    private String tagType;
    
    private String value;
    
    
    //------------------------ GETTERS --------------------------
    
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_enrichment_tag")
    @Override
    public int getId() {
        return id;
    }


    /**
     * The judgment that this tags adds information to.
     * @return
     */
    @ManyToOne
    public Judgment getJudgment() {
        return judgment;
    }


    /**
     * Tag type which specifies the sort of information provided by this tag. <br/> 
     * Not enum or other strict type in order to allow loose and independent cooperation between SAOS and SAOS Enricher System (
     * some tags generated by SAOS Enricher won't be used directly by SAOS but only exposed by RESTful API). The types recognizable
     * and used internally by SAOS are defined in {@link EnrichmentTagTypes}.
     */
    public String getTagType() {
        return tagType;
    }


    /**
     * String value of the tag in json format.
     */
    @Type(type = "StringJsonObject" )
    public String getValue() {
        return value;
    }
    
    
    
    //------------------------ SETTERS --------------------------


    public void setJudgment(Judgment judgment) {
        this.judgment = judgment;
    }


    public void setTagType(String tagType) {
        this.tagType = tagType;
    }


    public void setValue(String value) {
        this.value = value;
    }

    
    //------------------------ HashCode & Equals --------------------------
    
    
    @Override
    public int hashCode() {
        return Objects.hash(this.judgment, this.tagType, this.value);
    }
    
    
    @Override
    public boolean equals(Object obj) {
        
        if (obj == null) {
           return false;
        }
        
        if (getClass() != obj.getClass()) {
           return false;
        }
        
        final EnrichmentTag other = (EnrichmentTag) obj;
        
        return Objects.equals(this.judgment, other.judgment)
                && Objects.equals(this.tagType, other.tagType)
                && Objects.equals(this.value, other.value);

    }


   
    
    //------------------------ toString --------------------------
    
    @Override
    public String toString() {
        return "JudgmentCorrection [judgmentId=" + judgment.getId()
                + ", tagType=" + tagType
                + ", value=" + value + "]";
    }


 


}
