package pl.edu.icm.saos.api.services.representations.success.template;

/**
 * @author Łukasz Dumiszewski
 */

public class WithGeneratedTemplate extends QueryParameterRepresentation<Boolean, boolean[]> {
    private static final long serialVersionUID = 770006168279778528L;

    //------------------------ CONSTRUCTORS --------------------------
    public WithGeneratedTemplate(Boolean value) {
        super(value);
        setDescription("Tells whether the data generated by SAOS should be added to the dump, defaults to true");
        setAllowedValues(new boolean[]{true, false});
    }
}
