package pl.edu.icm.saos.importer.notapi;

/**
 * This package provides functionality of imports not based on specialized api, but for example
 * from files generated by us from html or pdfs 
 * 
 * Some data is imported from generated files, because at the time of writing this importer
 * certain courts did not provide any API for downloading the judgment data in a sensible
 * format.
 * 
 * */
