insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '03', 'Cywilny');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '06', 'Karny');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '09', 'Cywilny Rodzinny');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '12', 'Rodzinny i Nieletnich');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '15', 'Pracy');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '18', 'Ubezpieczeń Społecznych');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '21', 'Pracy i Ubezpieczeń Społecznych');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '24', 'Ksiąg Wieczystych');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '27', 'Gospodarczy');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '30', 'Gospodarczy Rejestrowy');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '33', 'Gospodarczy Rejestru Zastawów');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '36', 'Krajowego Rejestru Sądowego');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '39', 'Penitencjarny i Nadzoru nad Wykonywaniem Orzeczeń Karnych');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '42', 'Grodzki');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '45', 'Antymonopolowy');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '48', 'Spraw Geologicznych i Górniczych');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '51', 'Egzekucyjny');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '54', 'Wykonawczy');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '57', 'Wizytacyjny');
insert into common_court_division_type(id, creation_date, ver, code, name) values(nextval('seq_cc_division_type'), now(), 0, '60', 'Lustracyjny');
